
INSERT INTO connaissance (intitule,type) VALUES('Microstation / CAD TDO','I');
INSERT INTO connaissance (intitule,type) VALUES('Plantspace','I');
INSERT INTO connaissance (intitule,type) VALUES('Support Modeleur','I');
INSERT INTO connaissance (intitule,type) VALUES('Autopipe Vessel','I');
INSERT INTO connaissance (intitule,type) VALUES('ISO Extractor','I');
INSERT INTO connaissance (intitule,type) VALUES('Autocad','I');
INSERT INTO connaissance (intitule,type) VALUES('Robot Milenium','I');
INSERT INTO connaissance (intitule,type) VALUES('Sicap','I');
INSERT INTO connaissance (intitule,type) VALUES('FluidFlow','I');
INSERT INTO connaissance (intitule,type) VALUES('Caesar II','I');
INSERT INTO connaissance (intitule,type) VALUES('Magics','I');
INSERT INTO connaissance (intitule,type) VALUES('MS Project','I');
INSERT INTO connaissance (intitule,type) VALUES('EBP Gestion Commerciale','I');

INSERT INTO connaissance (intitule,type) VALUES('Conduite d\'affaires - Réunion lancement/avancement','T');
INSERT INTO connaissance (intitule,type) VALUES('Conduite d\'affaires - Réalisation planning et reporting','T');
INSERT INTO connaissance (intitule,type) VALUES('Conduite d\'affaires - Revue maquette','T');
INSERT INTO connaissance (intitule,type) VALUES('Conduite d\'affaires - MAJ documents (PIDS, ISOS, Plans, ...)','T');
INSERT INTO connaissance (intitule,type) VALUES('Conduite d\'affaires - Vérification documents (PIDS, ISOS, Plans, ...)','T');
INSERT INTO connaissance (intitule,type) VALUES('Conduite d\'affaires - Constitution de DFA','T');
INSERT INTO connaissance (intitule,type) VALUES('Conduite d\'affaires - Contrôle DFA','T');
INSERT INTO connaissance (intitule,type) VALUES('Tuyauterie/Chaudronnerie - Relevés','T');
INSERT INTO connaissance (intitule,type) VALUES('Tuyauterie/Chaudronnerie - Modélisation','T');
INSERT INTO connaissance (intitule,type) VALUES('Tuyauterie/Chaudronnerie - Calculs','T');
INSERT INTO connaissance (intitule,type) VALUES('Tuyauterie/Chaudronnerie - Vérification spécification matériel','T');
INSERT INTO connaissance (intitule,type) VALUES('Structure - Relevés','T');
INSERT INTO connaissance (intitule,type) VALUES('Structure - Modélisation','T');
INSERT INTO connaissance (intitule,type) VALUES('Structure - Calculs','T');
INSERT INTO connaissance (intitule,type) VALUES('Structure - Calcul au séisme','T');
INSERT INTO connaissance (intitule,type) VALUES('Génie Civil - Relevés','T');
INSERT INTO connaissance (intitule,type) VALUES('Génie Civil - Modélisation','T');
INSERT INTO connaissance (intitule,type) VALUES('Génie Civil - Vérification spécification travaux','T');
INSERT INTO connaissance (intitule,type) VALUES('Suivi de Chantier','T');
INSERT INTO connaissance (intitule,type) VALUES('CA Projet ARKEMA','T');
INSERT INTO connaissance (intitule,type) VALUES('CA Projet TOTAL Pau','T');
INSERT INTO connaissance (intitule,type) VALUES('CA Clé en main','T');
INSERT INTO connaissance (intitule,type) VALUES('Process','T');
INSERT INTO connaissance (intitule,type) VALUES('Audit Interne','T');
INSERT INTO connaissance (intitule,type) VALUES('Management par projet','T');
INSERT INTO connaissance (intitule,type) VALUES('Arbre des causes','T');
INSERT INTO connaissance (intitule,type) VALUES('Compagnonage/Formation interne/Tuteur(métier sécurité)','T');

INSERT INTO connaissance (intitule,type) VALUES('GSI Niveau 1','H');
INSERT INTO connaissance (intitule,type) VALUES('GSI Niveau 2','H');
INSERT INTO connaissance (intitule,type) VALUES('SOBEGI Lacq','H');
INSERT INTO connaissance (intitule,type) VALUES('SOBEGI Mourenx','H');
INSERT INTO connaissance (intitule,type) VALUES('TOTAL CSTJF','H');
INSERT INTO connaissance (intitule,type) VALUES('TIGF Lussagnet','H');
INSERT INTO connaissance (intitule,type) VALUES('Sécurité ERTech','H');
INSERT INTO connaissance (intitule,type) VALUES('Superviseur travaux (SOBEGI Lacq/Mourenx)','H');
INSERT INTO connaissance (intitule,type) VALUES('Utilisation échafaudages','H');
INSERT INTO connaissance (intitule,type) VALUES('Réception échafaudage','H');
INSERT INTO connaissance (intitule,type) VALUES('Sensibilisation ATEX','H');
INSERT INTO connaissance (intitule,type) VALUES('Port ARI','H');
INSERT INTO connaissance (intitule,type) VALUES('OPPBTP Encadrant','H');
INSERT INTO connaissance (intitule,type) VALUES('Sauveteur Secouriste du Travail','H');
INSERT INTO connaissance (intitule,type) VALUES('Electricité: BO-HO-HOV Très basse tension','H');
INSERT INTO connaissance (intitule,type) VALUES('Electricité: BR Basse tension','H');
INSERT INTO connaissance (intitule,type) VALUES('Utilisation extincteurs','H');

INSERT INTO connaissance (intitule,type) VALUES('Gestion d\'entreprise','G');
INSERT INTO connaissance (intitule,type) VALUES('Gestion ressources humaines','G');
INSERT INTO connaissance (intitule,type) VALUES('Gestion stratégie d\'entreprise','G');
INSERT INTO connaissance (intitule,type) VALUES('Superviseur et coordinateur des services','G');
INSERT INTO connaissance (intitule,type) VALUES('Démarche commerciale','G');
INSERT INTO connaissance (intitule,type) VALUES('Relation clients','G');
INSERT INTO connaissance (intitule,type) VALUES('Gestion comptabilité','G');
INSERT INTO connaissance (intitule,type) VALUES('Gestion paye','G');
INSERT INTO connaissance (intitule,type) VALUES('Gestion système QSSE','G');

INSERT INTO connaissance (intitule,type) VALUES('Pharmacie','S');
INSERT INTO connaissance (intitule,type) VALUES('Pétrochimie','S');
INSERT INTO connaissance (intitule,type) VALUES('Ferroviaire','S');
INSERT INTO connaissance (intitule,type) VALUES('Agroalimentaire','S');
INSERT INTO connaissance (intitule,type) VALUES('Raffinage','S');
INSERT INTO connaissance (intitule,type) VALUES('Chimie','S');
INSERT INTO connaissance (intitule,type) VALUES('Automobile','S');
INSERT INTO connaissance (intitule,type) VALUES('Gaz','S');

INSERT INTO connaissance (intitule,type) VALUES('Anglais','L');
INSERT INTO connaissance (intitule,type) VALUES('Espagnol','L');
INSERT INTO connaissance (intitule,type) VALUES('Allemand','L');
